import SuperAdminDocumentVerificationDashboard from './SuperAdminDocumentVerificationDashboard';
export const AdminDocumentVerificationDashboard = SuperAdminDocumentVerificationDashboard;
export default SuperAdminDocumentVerificationDashboard;
