import SuperAdminDocumentVerificationDashboard from './SuperAdminDocumentVerificationDashboard';
export const OperationsDocumentVerificationDashboard = SuperAdminDocumentVerificationDashboard;
export default SuperAdminDocumentVerificationDashboard;
